#!/usr/bin/env bash
# Configure nginx server to redirect '/redirect_me' to another page

#Installing nginx if not present
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"                                                                                                                                                                                                                               # Modify the Nginx configuration file to set up the redirection
sudo sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-enabled/default 

sudo servicv ngin_ restart
sudo service nginx reload
