#!/usr/bin/env bash
# Configure nginx server to redirect '/redirect_me' to another page

#Installing nginx if not present
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

# Create a backup of the default nginx config file
redirect = "\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
# Modify the config file to set up redirection
sudo sed -i "26i $redirect" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
